# Generated by Django 5.0.1 on 2024-01-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_dev", "0002_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
